version: '3.5'

services:
  userwrite:
    image: jeffotoni/userwrite:latest
    container_name: userwrite
    hostname: userwrite
    domainname: userwrite.local.com
    environment:
      - "TZ=America/Sao_Paulo"
      - "API_ENV=prod"
      - "MONGODB_USERNAME=root"
      - "MONGODB_PASSWORD=123456"
      - "MONGODB_URI=mongodb.local.com:27017"
      - "MONGODB_OPTIONS=authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false"
    networks:
        gmeli:
           aliases:
              - userwrite.local.com
    ports:
      - 8081:8081
    # depends_on:
    #   - mongo-users
    restart: always

  userget:
      image: jeffotoni/userget:latest
      container_name: userget
      hostname: userget
      domainname: userget.local.com
      environment:
        - "TZ=America/Sao_Paulo"
        - "API_ENV=prod"
        - "MONGODB_USERNAME=root"
        - "MONGODB_PASSWORD=123456"
        - "MONGODB_URI=mongodb.local.com:27017"
        - "MONGODB_OPTIONS=authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false"
        - "REDIS_ADDR=redis.local.com:6379"
        - "REDIS_PASSWORD="
      networks:
          gmeli:
             aliases:
                - userget.local.com
      ports:
        - 8082:8082
      depends_on:
        - mongo-users
        - redis
      restart: always

  mongo-users:
    image: mongo:latest
    volumes:
      - ./mongo.script:/mnt/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: meliusers
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    networks:
        gmeli:
            aliases:
              - mongodb.local.com
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      gmeli:
            aliases:
              - redis.local.com


  # proxy:
  #   image: nginx
  #   volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #    - "8080:80"
  #   environment:
  #    - NGINX_HOST=localhost
  #    - NGINX_PORT=8080

networks:
  gmeli:
      driver: bridge
