swagger: '2.0'
info:
  version: ''
  title: swagger
  description: ''
paths:
  /v1/user:
    post:
      operationId: POST_v1-user
      summary: /v1/user
      consumes:
        - text/plain
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              birthday:
                type: string
              cpf:
                type: string
              email:
                type: string
              password:
                type: string
            example:
              first_name: Jefferson
              last_name: Otoni
              birthday: '1945-08-20'
              cpf: 039.876.696-75
              email: jeff.otoni@gmail.com
              password: '123456'
        - name: Content-Type
          in: header
          required: false
          type: string
          default: ' application/json'
      responses:
        default:
          description: ''
          schema: {}
    get:
      operationId: GET_v1-user
      summary: /v1/user
      consumes:
        - text/plain
      parameters:
        - name: nome
          in: query
          required: false
          type: string
          default: jeff
        - name: email
          in: query
          required: false
          type: string
          default: jeff@
        - name: cpf
          in: query
          required: false
          type: string
          default: 03.987.748-05
        - name: Content-Type
          in: header
          required: false
          type: string
          default: ' application/json'
      responses:
        default:
          description: ''
          schema: {}
  '/v1/user/:id':
    put:
      operationId: 'PUT_v1-user-:id'
      summary: '/v1/user/:id'
      consumes:
        - text/plain
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              birthday:
                type: string
              cpf:
                type: string
              email:
                type: string
              password:
                type: string
            example:
              first_name: Jefferson
              last_name: Otoni
              birthday: '1945-08-20'
              cpf: 039.876.696-75
              email: jeff.otoni@gmail.com
              password: '123456'
        - name: Content-Type
          in: header
          required: false
          type: string
          default: ' application/json'
      responses:
        default:
          description: ''
          schema: {}
definitions: {}

